---
- name: Remove windows admin user
  hosts: windows
  vars:
    win_admin_user: "default"
    win_admin_pass: "default"
    
  tasks:
      
################### Local Admin from Controller ###################
    - name: Create Local Admin User
      ansible.windows.win_user:
        name: "{{ win_admin_user }}"
        password: "{{ win_admin_pass }}"
        password_never_expires: true   
        groups: Administrators
        state: absent
      register: localadministrator_result
