---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - manage-instances
  vars:
    teardown: false
  tasks:
    - include_role:
        name: "deploy-azure-linux"
  