---
- name: Augment a ServiceNow Incident
  hosts: localhost
  collections:
    - servicenow.itsm

  tasks:
    - name: Debug all vars
      ansible.builtin.debug:
        var: ansible_eda.event.sys_id
    - name: Set the incident number
      ansible.builtin.set_fact:
        inc_number: "{{ ansible_eda.event.number }}"
    - name: Set the sys_id
      ansible.builtin.set_fact:
        inc_sys_id: "{{ ansible_eda.event.sys_id }}"
    - name: Gather messages log
      ansible.builtin.shell: "echo '{{ dummy_messages_log }}' > /tmp/{{ inc_number }}_messages.log"
      register: messages_log
    - name: Gather journal /var/log/messages
      ansible.builtin.shell: "echo '{{ dummy_journal_log }}' > /tmp/{{ inc_number }}_journal.log"
      register: journal_log
    - name: All done message
      ansible.builtin.debug:
        msg: "Incident augmentation for incident {{ inc_number }} complete."