---
- name: Augment a ServiceNow Incident
  hosts: localhost
  vars: 
    inc_number: "{{ ansible_eda.event.number }}"
    inc_sys_id: "{{ ansible_eda.event.sys_id }}"

  tasks:
    - name: Debug all vars
      ansible.builtin.debug:
        var: inc_number
    - name: Gather messages log
      ansible.builtin.shell: "echo '{{ dummy_messages_log }}' > /tmp/{{ inc_number }}_messages.log"
      register: messages_log
    - name: Gather journal /var/log/messages
      ansible.builtin.shell: "echo '{{ dummy_journal_log }}' > /tmp/{{ inc_number }}_journal.log"
      register: journal_log
    - name: All done message
      ansible.builtin.debug:
        msg: "Incident augmentation for incident {{ inc_number }} complete."