---
- name: List all installed Programs
  hosts: windows
  tasks:
    - name: Gather list
      win_shell: Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table –AutoSize
      register: program_list

    - debug:
      msg: "{{ program_list.stdout.split('\n') }}"
